# ============
#   Functions
# ============

[build]
  functions = "functions/"
[dev]
  # command = "yarn start"
  port = 8888
  # targetPort = 3000
  publish = "public"
  autoLaunch = true

[[redirects]]
  from = "/ourclients/"
  to = "/clients/"
  status = 301

[[redirects]]
  from = "/content/*"
  to = "/insights/"
  status = 301

[[redirects]]
  from = "/ourteam/"
  to = "/team/"
  status = 301

[[redirects]]
  from = "/howwework/"
  to = "/"
  status = 301